Import('env')

env = env.Clone()

env.Install(
    target='include/derived',
    source=[
        'derived.h',
    ],
    INSTALL_TAGS=[
        'dev',
    ]
)

env.Library(
    target='derived',
    source=[
        'derived.cpp',
    ],
    LIBS=[
        '$BUILD_DIR/$VARIANT_DIR/base/base',
    ],
)
