Import('env')

derivedHeaders = env.File([
    'derived.h',
])
installDerivedHeaders = env.Install('$PREFIX/include/derived', derivedHeaders)
env.Alias('install-dev', installDerivedHeaders)

derivedLib = env.SharedLibrary(
    target='derived',
    source=[
        'derived.cpp',
    ],
    LIBS=[
        'base',
    ],
    CPPDEFINES=[
         "HYGENIC_DEMO_API_LIBDERIVED",
    ],
)
