Import('env')

env = env.Clone()

env.Install(
    target='include/derived',
    source=[
        'derived.h',
    ],
    INSTALL_TAGS=[
        'dev',
    ]
)

env.SharedLibrary(
    target='derived',
    source=[
        'derived.cpp',
    ],
    LIBS=[
        'base',
    ],
    CPPDEFINES=[
         "HYGENIC_DEMO_API_LIBDERIVED",
    ],
)
