Import('env')

env = env.Clone()

env.AppendUnique(
    CPPPATH=['#/src'],
)

if not 'MSVC_VERSION' in env:
    env.AppendUnique(
        CXXFLAGS=[
            '-std=c++11',
        ],
    )

env.SConscript(
    dirs=[
        'base',
        'derived',
    ],
    exports=[
        'env'
    ],
)

env.Install(
    target='include',
    source=[
        'config.h'
    ],
    INSTALL_TAGS=[
        'dev',
    ],
)

env.Program(
    target='main',
    source=[
        'main.cpp',
    ],
    LIBS=[
        '$BUILD_DIR/$VARIANT_DIR/derived/derived',
        '$BUILD_DIR/$VARIANT_DIR/base/base',
    ],
    INSTALL_TAGS=[
        'default',
    ]
)
