Import('env')

baseLib = env.SharedLibrary(
    target='base',
    source=[
        'base.cpp',
    ],
    CPPDEFINES=[
        "HYGENIC_DEMO_API_LIBBASE",
    ],
)

installBaseLib = env.Install('$PREFIX/lib', baseLib)
env.Alias('install-libs', installBaseLib)
