Import('env')

env = env.Clone()

env.Install(
    target='include/base',
    source=[
        'base.h',
    ],
    INSTALL_TAGS=[
        'dev'
    ],
)

env.SharedLibrary(
    target='base',
    source=[
        'base.cpp',
    ],
    CPPDEFINES=[
        "HYGENIC_DEMO_API_LIBBASE",
    ],
)
