Import('env')

baseHeaders = env.File([
    'base.h',
])
installBaseHeaders = env.Install('$PREFIX/include/base', baseHeaders)
env.Alias('install-dev', installBaseHeaders)

baseLib = env.SharedLibrary(
    target='base',
    source=[
        'base.cpp',
    ],
    CPPDEFINES=[
        "HYGENIC_DEMO_API_LIBBASE",
    ],
)

installBaseLib = env.Install('$PREFIX/lib/base', baseLib)
env.Alias('install-libs', installBaseLib)
